package simulator.client.gui.editor;

import simulator.client.gui.GameJoinDialog;

/**
 *
 * @author 82wach1bif
 */
public class SimulatorEditor extends javax.swing.JFrame {

    /**
     * Creates new form SimulatorEditor
     */
    public SimulatorEditor() {
        initComponents();
        setLocationRelativeTo(null);
        
        jToggleButtonInner.setSelected(true);
        
        jToggleButtonInner.addActionListener((a) -> {
            jToggleButtonOutter.setSelected(false);
            jToggleButtonStart.setSelected(false);
            mapEditComponent.selectInner();
        });
        
        jToggleButtonOutter.addActionListener((a) -> {
            jToggleButtonInner.setSelected(false);
            jToggleButtonStart.setSelected(false);
            mapEditComponent.selectOutter();
        });
        
        jToggleButtonStart.addActionListener((a) -> {
            jToggleButtonInner.setSelected(false);
            jToggleButtonOutter.setSelected(false);
            mapEditComponent.selectStart();
        });
    }
    
    public static void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameJoinDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameJoinDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameJoinDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameJoinDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SimulatorEditor editor = new SimulatorEditor();
            editor.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonInner = new javax.swing.JToggleButton();
        jToggleButtonOutter = new javax.swing.JToggleButton();
        jToggleButtonStart = new javax.swing.JToggleButton();
        mapEditComponent = new simulator.client.gui.editor.MapEditComponent();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemUpload = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulator - Editor");

        jToolBar1.setRollover(true);

        jToggleButtonInner.setText("Inner");
        jToggleButtonInner.setFocusable(false);
        jToggleButtonInner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonInner.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonInner);

        jToggleButtonOutter.setText("Outter");
        jToggleButtonOutter.setFocusable(false);
        jToggleButtonOutter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonOutter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonOutter);

        jToggleButtonStart.setText("Start");
        jToggleButtonStart.setFocusable(false);
        jToggleButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonStart);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout mapEditComponentLayout = new javax.swing.GroupLayout(mapEditComponent);
        mapEditComponent.setLayout(mapEditComponentLayout);
        mapEditComponentLayout.setHorizontalGroup(
            mapEditComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        mapEditComponentLayout.setVerticalGroup(
            mapEditComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        getContentPane().add(mapEditComponent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItemOpen.setText("Öffne Karte");
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setText("Speicher Karte");
        jMenu1.add(jMenuItemSave);

        jMenuItemUpload.setText("Karte hochladen");
        jMenu1.add(jMenuItemUpload);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemUpload;
    private javax.swing.JToggleButton jToggleButtonInner;
    private javax.swing.JToggleButton jToggleButtonOutter;
    private javax.swing.JToggleButton jToggleButtonStart;
    private javax.swing.JToolBar jToolBar1;
    private simulator.client.gui.editor.MapEditComponent mapEditComponent;
    // End of variables declaration//GEN-END:variables
}
