package simulator.client.gui;

import simulator.client.gui.editor.SimulatorEditor;
import java.awt.Color;
import java.awt.EventQueue;
import simulator.Point;
import simulator.SimulatorMap;
import simulator.client.MultiplayerLogic;

import javax.swing.*;

/**
 *
 * @author 82wach1bif
 */
public class SimulatorFrame extends JFrame {

    private MultiplayerLogic logic;

    private class LogicListener implements MultiplayerLogic.Listener {

        @Override
        public void onMessage(String msg) {
            jTextAreaMessages.setText(jTextAreaMessages.getText() + msg + "\n");

            EventQueue.invokeLater(() -> {
                JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
                vertical.setValue(vertical.getMaximum());
            });
        }

        @Override
        public void onMapLoaded(SimulatorMap map) {
            mapComponent.setMap(map);
        }

        @Override
        public void onPlayerTurn(Point point, Color color) {
            mapComponent.onPlayerTurn(point, color);
        }

        @Override
        public void onGameFinished() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void onGameStateChange() {
            jMenuItemGameJoin.setEnabled(logic.isConnected() && !logic.isInGame());
            jMenuItemGameStart.setEnabled(logic.isConnected() && !logic.isInGame());
            jMenuItemGameQuit.setEnabled(logic.isInGame());
        }

        @Override
        public void awaitPlayerTurn(Point point) {
            mapComponent.requestFocus();
            mapComponent.awaitPlayerTurn(point, (turn) -> {
                logic.setPlayerTurn(turn);
            });
        }

        @Override
        public void onReset() {
           mapComponent.reset();
        }
    }

    /**
     * Creates new form SimulatorFrame
     */
    public SimulatorFrame() {
        initComponents();
        setLocationRelativeTo(null);
        logic = new MultiplayerLogic(new LogicListener());
        logic.connect("localhost");

        jMenuItemOpenEditor.addActionListener((a) -> {
            SimulatorEditor.open(logic::uploadMap);
        });

        jMenuItemGameStart.addActionListener((a) -> {
            GameCreateDialog.openDialog(this, logic);
        });

        jMenuItemGameQuit.addActionListener((a) -> {
            logic.exitGame();
        });

        jMenuItemGameJoin.addActionListener((a) -> {
            GameJoinDialog.openDialog(this, logic);
        });

        jTextFieldMessage.addActionListener((a) -> {
            logic.sendMessage(jTextFieldMessage.getText());
            jTextFieldMessage.setText("");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // CHECKSTYLE:OFF
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextAreaMessages = new javax.swing.JTextArea();
        jTextFieldMessage = new javax.swing.JTextField();
        mapComponent = new simulator.client.gui.MapComponent();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpenEditor = new javax.swing.JMenuItem();
        jMenuItemGameStart = new javax.swing.JMenuItem();
        jMenuItemGameJoin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGameQuit = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulator");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jTextAreaMessages.setEditable(false);
        jTextAreaMessages.setColumns(20);
        jTextAreaMessages.setRows(5);
        jPanel1.add(jTextAreaMessages);
        jPanel1.add(jTextFieldMessage);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout mapComponentLayout = new javax.swing.GroupLayout(mapComponent);
        mapComponent.setLayout(mapComponentLayout);
        mapComponentLayout.setHorizontalGroup(
            mapComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        mapComponentLayout.setVerticalGroup(
            mapComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        getContentPane().add(mapComponent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Spiel");

        jMenuItemOpenEditor.setText("Öffne Editor");
        jMenu1.add(jMenuItemOpenEditor);

        jMenuItemGameStart.setText("Spiel starten");
        jMenu1.add(jMenuItemGameStart);

        jMenuItemGameJoin.setText("Spiel beitreten");
        jMenu1.add(jMenuItemGameJoin);
        jMenu1.add(jSeparator1);

        jMenuItemGameQuit.setText("Beenden");
        jMenu1.add(jMenuItemGameQuit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SimulatorFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemGameJoin;
    private javax.swing.JMenuItem jMenuItemGameQuit;
    private javax.swing.JMenuItem jMenuItemGameStart;
    private javax.swing.JMenuItem jMenuItemOpenEditor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaMessages;
    private javax.swing.JTextField jTextFieldMessage;
    private simulator.client.gui.MapComponent mapComponent;
    // End of variables declaration//GEN-END:variables
}
